sveltejs/eslint-plugin-svelte

docs/rules/no-unknown-style-directive-property.md
src/rules/no-unused-svelte-ignore.ts
src/shared/svelte-compile-warns.ts
tests/fixtures/rules/no-unused-svelte-ignore/valid/style-lang01-input.svelte
tests/fixtures/rules/no-unused-svelte-ignore/valid/style-lang02-input.svelte
tests/fixtures/rules/valid-compile/valid/style-lang01-input.svelte
tests/fixtures/rules/valid-compile/valid/style-lang02-input.svelte

Fix false positives for extend style lang attributes in rules that use compilation

---

src/shared/svelte-compile-warns.ts
tests/fixtures/rules/valid-compile/valid/ts/type-only-import01-input.svelte
tests/fixtures/rules/valid-compile/valid/ts/type-only-import02-input.svelte

Fix false positives for type-only import in rules that use compilation

---

docs/rules/comment-directive.md
src/rules/comment-directive.ts
tests/src/rules/comment-directive.ts

This PR adds `reportUnusedDisableDirectives` option to `svelte/comment-directive` rule.
---
I had implemented this option halfway, but I realized I didn't finish the implementation 😓.

Add `reportUnusedDisableDirectives` option to `svelte/comment-directive` rule

---

package.json
renovate.json

This PR fixes the version of `@sveltejs/kit` as a workaround for the site build error.
It takes time to work to upgrade the version.

Chore: fixed ver of `@sveltejs/kit`

---

src/rules/prefer-class-directive.ts
src/rules/prefer-style-directive.ts
src/utils/ast-utils.ts
tests/fixtures/rules/prefer-class-directive/invalid/svelte-element01-errors.json
tests/fixtures/rules/prefer-class-directive/invalid/svelte-element01-input.svelte
tests/fixtures/rules/prefer-class-directive/invalid/svelte-element01-output.svelte
tests/fixtures/rules/prefer-class-directive/valid/ignore-component01-input.svelte
tests/fixtures/rules/prefer-class-directive/valid/ignore-svelte-self01-input.svelte

Fix false positives for component in `prefer-class-directive` rule

---

docs/rules/indent.md
src/rules/indent-helpers/commons.ts
src/rules/indent-helpers/index.ts
src/rules/indent-helpers/svelte.ts
src/rules/indent.ts
tests/fixtures/rules/indent/invalid/indent-script/_config.json
tests/fixtures/rules/indent/invalid/indent-script/indent-script-errors.json
tests/fixtures/rules/indent/invalid/indent-script/indent-script-input.svelte
tests/fixtures/rules/indent/invalid/indent-script/indent-script-output.svelte
tests/fixtures/rules/indent/valid/indent-script-input.svelte

Allows for configuring whether the contents of `<script>` blocks should be indented a single tabstop or not. Defaults to `true` for back-compat.
Fixes #155

feat: indent/indentScript option

---

README.md
docs/user-guide.md
src/configs/prettier.ts
src/index.ts
src/rules/first-attribute-linebreak.ts
src/rules/html-quotes.ts
src/rules/indent.ts
src/rules/max-attributes-per-line.ts
src/rules/mustache-spacing.ts
src/rules/prefer-class-directive.ts
src/rules/prefer-style-directive.ts
src/rules/shorthand-attribute.ts
src/rules/shorthand-directive.ts
src/rules/spaced-html-comment.ts
src/types.ts
tools/update-rulesets.ts

This PR adds `plugin:svelte/prettier` config that turns off rules that conflict with prettier-plugin-svelte.

Add `plugin:svelte/prettier` config

---

docs-svelte-kit/src/lib/components/ESLintPlayground.svelte

Now playground width is too narorow.
To fix this issue, we need to override the layout svelte file's CSS in some way.
However, I could not figure out how to do it because of the markdown involved.
So I used `:global` to solve this issue.
I could not find a way not to use `!important`.

Docs: Fix playground width

---

README.md
docs/rules.md
docs/rules/no-spaces-around-equal-signs-in-attribute.md
src/configs/prettier.ts
src/rules/no-spaces-around-equal-signs-in-attribute.ts
src/utils/rules.ts
tests/fixtures/rules/no-spaces-around-equal-signs-in-attribute/invalid/test01-errors.json
tests/fixtures/rules/no-spaces-around-equal-signs-in-attribute/invalid/test01-input.svelte
tests/fixtures/rules/no-spaces-around-equal-signs-in-attribute/invalid/test01-output.svelte
tests/fixtures/rules/no-spaces-around-equal-signs-in-attribute/valid/test-01-input.svelte
tests/src/rules/no-spaces-around-equal-signs-in-attribute.ts

Moved to separate PR from ota-meshi/eslint-plugin-svelte#186
Also a simple rule which automatically removes spaces around attribute equal signs
```html
<div class ="test" />
<div class="test" />
```
I had difficulties with this rule, as `SvelteAttribute` has only key and value, but with some regex magic the rule should work.
100% test coverage.

feat: add `svelte/no-spaces-around-equal-signs-in-attribute`

---

src/rules/no-unused-svelte-ignore.ts
tests/fixtures/rules/no-unused-svelte-ignore/valid/ignore-js-input.js
tests/utils/utils.ts

This PR fixes a false positive in the `svelte/no-unused-svelte-ignore` rule for JS files.
The rule should not check for files other than those parsed by svelte-eslint-parser.
I also changed the test utility so that it can target fixtures other than .svelte.

Fix false positives for files other than `*.svelte` in `svelte/no-unused-svelte-ignore` rule

---

README.md
docs/rules.md
docs/rules/no-reactive-literals.md
src/rules/no-reactive-literals.ts
src/types.ts
src/utils/rules.ts
tests/fixtures/rules/no-reactive-literals/invalid/test01-errors.json
tests/fixtures/rules/no-reactive-literals/invalid/test01-input.svelte
tests/fixtures/rules/no-reactive-literals/invalid/test01-output.svelte
tests/fixtures/rules/no-reactive-literals/valid/test01-input.svelte
tests/src/rules/no-reactive-literals.ts
tests/utils/utils.ts

Porting over another of the simpler rules from https://github.com/tivac/eslint-plugin-svelte/ like we discussed in https://github.com/ota-meshi/eslint-plugin-svelte/issues/198

Add `svelte/no-reactive-literals` rule

---

src/rules/no-reactive-literals.ts
tests/fixtures/rules/no-reactive-literals/valid/test01-input.svelte

One of the suggestions on #203 was to use `:matches(...)` around an array `.join()` which somehow got only... halfway implemented. The `.join()` was there, but it was missing the `:matches(...)` around it which could lead to some pretty bad false positives.
Added back the `:matches(...)` and added a few more valid test-cases to watch out for false-positives like this going forward.

fix: `no-reactive-literals` using `:matches(...)`

---

README.md
docs/rules.md
docs/rules/no-reactive-functions.md
src/rules/no-reactive-functions.ts
src/utils/rules.ts
tests/fixtures/rules/no-reactive-functions/invalid/test01-errors.json
tests/fixtures/rules/no-reactive-functions/invalid/test01-input.svelte
tests/fixtures/rules/no-reactive-functions/valid/test01-input.svelte
tests/src/rules/no-reactive-functions.ts

This rule reports whenever a function is defined in a reactive statement. This isn't necessary, as each time the function is executed it'll already have access to the latest values necessary. Redefining the function in the reactive statement is just a waste of CPU cycles.
```svelte
<script>
/* eslint svelte/no-reactive-functions: "error" */
/* ✓ GOOD */
const arrowFn = () => { /* ... */ }
const func = function() { /* ... */ }
/* ✗ BAD */
$: arrowFn = () => { /* ... */ }
$: func = function() { /* ... */ }
</script>
```

add `no-reactive-functions` rule

---

.github/workflows/GHPages.yml
svelte.config.mjs
vite.config.mts

This PR fixes compilation issues on the docs site dev server when using the latest svelte-kit.

Chore: fix doc site script

---

docs-svelte-kit/build-system/build.mts
svelte.config.mjs
vite.config.mts

This PR fixes `docs:watch` to work on Windows.
It seems I didn't understand how to use `import.meta.url` properly.

Chore: Fix `docs:watch` to work on Windows

---

README.md
docs-svelte-kit/src/lib/components/ESLintCodeBlock.svelte
docs-svelte-kit/src/lib/eslint/ESLintEditor.svelte
docs/rules.md
docs/rules/require-stores-init.md
package.json
src/rules/require-stores-init.ts
src/utils/rules.ts
tests/fixtures/rules/.eslintrc.js
tests/fixtures/rules/indent/invalid/.eslintrc.js
tests/fixtures/rules/no-unused-svelte-ignore/valid/.eslintrc.js
tests/fixtures/rules/require-stores-init/invalid/no-init-in-js01-errors.yaml
tests/fixtures/rules/require-stores-init/invalid/no-init-in-js01-input.js
tests/fixtures/rules/require-stores-init/invalid/no-init01-errors.yaml
tests/fixtures/rules/require-stores-init/invalid/no-init01-input.svelte
tests/fixtures/rules/require-stores-init/valid/has-init-in-js01-input.js
tests/fixtures/rules/require-stores-init/valid/has-init01-input.svelte
tests/fixtures/rules/require-stores-init/valid/no-svelte-store01-input.svelte
tests/fixtures/rules/require-stores-init/valid/spread01-input.svelte
tests/src/rules/require-stores-init.ts
tests/utils/utils.ts
typings/eslint-utils/index.d.ts

This PR adds `svelte/require-stores-init` rule that require initial value in store.
This rule was taken from  `@tivac/svelte/stores-initial-value` rule.
However, no suggestions are provided.
The original suggestion is to give `false` as the argument, but I think the least code-breaking suggestion is to give `undefined` as the argument. But for most users it makes no sense to give `undefined`.

Add `svelte/require-stores-init` rule

---

src/rules/no-reactive-functions.ts
src/rules/no-reactive-literals.ts

see https://github.com/ota-meshi/eslint-plugin-svelte/pull/186#discussion_r926289266
Rules added by @tivac have first letters in desceiption capitalized, which is inconsistent with the rest of the plugin.
This is also the case in #205 and #208.

docs: uncapitalized first letters in rule desceiptions

---

.changeset/curvy-ants-admire.md
README.md
docs/rules.md
docs/rules/no-store-async.md
src/rules/no-store-async.ts
src/rules/reference-helpers/svelte-store.ts
src/rules/require-stores-init.ts
src/utils/rules.ts
tests/fixtures/rules/no-store-async/invalid/test01-errors.yaml
tests/fixtures/rules/no-store-async/invalid/test01-input.js
tests/fixtures/rules/no-store-async/invalid/test02-errors.yaml
tests/fixtures/rules/no-store-async/invalid/test02-input.js
tests/fixtures/rules/no-store-async/invalid/test03-errors.yaml
tests/fixtures/rules/no-store-async/invalid/test03-input.js
tests/fixtures/rules/no-store-async/invalid/test04-errors.yaml
tests/fixtures/rules/no-store-async/invalid/test04-input.js
tests/fixtures/rules/no-store-async/valid/test01-input.js
tests/src/rules/no-store-async.ts

Related to: https://github.com/ota-meshi/eslint-plugin-svelte/issues/198 (`stores-no-async`)
This is the first ESLint rule I have written.
(So I'm sorry if I have a wrong understanding.)
I would be very grateful if you would review it.

feat: implement `stores-no-async`

---

.github/workflows/Release.yml
package.json

See https://github.com/ota-meshi/eslint-plugin-svelte/pull/235#issuecomment-1223395556

chore: change changesets config

---

src/rules/no-store-async.ts

This PR removes the no-store-async rule from the recommended configuration.
It should have been done in a major version upgrade as it is included in breaking changes.

fix: remove no-store-async rule from recommended config

---

.codesandbox/ci.json
package.json
tests/src/rules/indent.ts

It seems there was a breaking change in decorator nodes in ts4.8. Because of this some tests using typescript-eslint v4 fail so ignoring these tests.
---
It also fixes yarn install in codesandbox-ci failing because svelte kit no longer supports Node v16.13.

test: ignore indent test for decorators with ts4.8

---

package.json

vite 3.1-beta is now required for the latest svelte kit to work.
https://github.com/sveltejs/kit/pull/6398

chore: use vite v3.1-beta

---

.vscode/settings.json
tsconfig.json

This repo doesn't need to use vetur, so I removed it.

chore: remove unused vetur settings

---

.changeset/gentle-bugs-stare.md
README.md
docs/rules.md
docs/rules/derived-has-same-inputs-outputs.md
src/rules/derived-has-same-inputs-outputs.ts
src/rules/no-store-async.ts
src/rules/reference-helpers/svelte-store.ts
src/utils/rules.ts
tests/fixtures/rules/derived-has-same-inputs-outputs/invalid/test01-errors.yaml
tests/fixtures/rules/derived-has-same-inputs-outputs/invalid/test01-input.js
tests/fixtures/rules/derived-has-same-inputs-outputs/valid/test01-input.js
tests/src/rules/derived-has-same-inputs-outputs.ts

Related to: https://github.com/ota-meshi/eslint-plugin-svelte/issues/198 (derived-inputs-outputs)

feat: implement `derived-has-same-inputs-outputs`

---

svelte.config.mjs

Update `svelte.config.mjs` according to https://github.com/sveltejs/kit/pull/6586

chore: migrate config.kit.files.hooks

---

docs-svelte-kit/src/lib/components/ESLintCodeBlock.svelte
docs-svelte-kit/src/lib/eslint/ESLintEditor.svelte
docs-svelte-kit/src/lib/eslint/scripts/monaco-loader.js
docs-svelte-kit/src/lib/eslint/scripts/syntax.js

chore: improve svelte syntax in demo

---

docs/migration.md

fix: https://github.com/ota-meshi/eslint-plugin-svelte/issues/252
Honestly, I couldn't find difficulties in migrating from `eslint-plugin-svelte3`.
But preparing this section is essential for new users.
In the future, I will follow it up in the docs if some new user hits difficulties.
And I handled https://github.com/sveltejs/kit/issues/6847#issuecomment-1251471651 in the PR.

chore: add migration guide from eslint-plugin-svelte3

---

.changeset/fluffy-chicken-happen.md
README.md
docs/rules.md
docs/rules/require-store-callbacks-use-set-param.md
package.json
src/rules/require-store-callbacks-use-set-param.ts
src/utils/rules.ts
tests/fixtures/rules/html-self-closing/invalid/presets/html/preset-html-errors.yaml
tests/fixtures/rules/html-self-closing/invalid/presets/none/preset-none-errors.yaml
tests/fixtures/rules/require-store-callbacks-use-set-param/invalid/test01-errors.yaml
tests/fixtures/rules/require-store-callbacks-use-set-param/invalid/test01-input.svelte
tests/fixtures/rules/require-store-callbacks-use-set-param/invalid/test02-errors.yaml
tests/fixtures/rules/require-store-callbacks-use-set-param/invalid/test02-input.svelte
tests/fixtures/rules/require-store-callbacks-use-set-param/valid/test01-input.svelte
tests/fixtures/rules/require-store-callbacks-use-set-param/valid/test02-input.svelte
tests/src/rules/require-store-callbacks-use-set-param.ts

resolve: https://github.com/ota-meshi/eslint-plugin-svelte/issues/267

feat: Add `require-store-callbacks-use-set-param` rule

---

README.md
docs/rules.md
docs/rules/no-export-load-in-svelte-module-in-kit-pages.md
docs/rules/require-store-callbacks-use-set-param.md
docs/user-guide.md
src/types.ts
src/utils/svelte-kit.ts
tests/fixtures/rules/no-export-load-in-svelte-module-in-kit-pages/invalid/_config.json
tests/fixtures/rules/no-export-load-in-svelte-module-in-kit-pages/valid/_config.json
tests/fixtures/rules/no-export-load-in-svelte-module-in-kit-pages/valid/not-page/_config.json

This PR renames the settings in `settings.kit` to `settings.svelte.kit`.
There is no convention for the namespace under `settings`, but it's common for the community to use the name of the plugin.
I didn't notice that in the reviews 😓.
cc: @baseballyama 
Sorry 😓. This also affects #283.
https://eslint.org/docs/latest/user-guide/configuring/configuration-files#adding-shared-settings

refactor: rename `settings.kit` to `settings.svelte.kit`

---

src/rules/@typescript-eslint/no-unnecessary-condition.ts
src/rules/prefer-destructured-store-props.ts
src/rules/reference-helpers/svelte-store.ts
src/types.ts
src/utils/ast-utils.ts
typings/eslint-utils/index.d.ts

This PR is a follow up to #294.
I forgot to migrate Scope related types.

refactor: use `@typescript-eslint/scope-manager` instead of `eslint-scope`

---

.changeset/fix-isKitPageComponent-on-windows.md
src/utils/svelte-kit.ts

it always returned `false` on windows because file paths are separated by `\` instead of `/`

fix `isKitPageComponent` on windows

---

package.json

This PR works around the playground freezing issue.
The cause of the problem is a bug in rollup v3.7. The workaround is to use rollup v3.6 instead.
https://github.com/rollup/rollup/pull/4742
https://github.com/vitejs/vite/issues/11330
---
close #317

chore: fix playground

---

package.json

This PR reverts the #322 change. The workaround is no longer needed as the rollup has been fixed.

chore: remove workaround for playground

---

src/rules/@typescript-eslint/no-unnecessary-condition.ts

I run `yarn build` on the latest main branch, but command failed due to type error.
Therefore I fixed it up.
```sh
baseballyama@baseballyama eslint-plugin-svelte % yarn build
yarn run v1.22.19
$ yarn clean
$ rimraf .nyc_output lib coverage build .svelte-kit svelte.config-dist.js
$ yarn build:ts
$ tsc --project ./tsconfig.build.json
src/rules/@typescript-eslint/no-unnecessary-condition.ts:749:34 - error TS2345: Argument of type 'ArrayExpression | ArrayPattern | ArrowFunctionExpression | AssignmentExpression | AwaitExpression | ... 35 more ... | YieldExpression' is not assignable to parameter of type 'LeftHandSideExpression'.
Type 'AssignmentExpression' is not assignable to type 'LeftHandSideExpression'.
Type 'AssignmentExpression' is missing the following properties from type …
```

fix: types of `isOptionableExpression`

---

docs-svelte-kit/src/lib/eslint/MonacoEditor.svelte

fix: https://github.com/ota-meshi/eslint-plugin-svelte/issues/331

chore: Enable user scroll even if mouse is on a Monaco editor

---

.changeset/nice-buses-repeat.md
src/rules/valid-prop-names-in-kit-pages.ts
tests/fixtures/rules/valid-prop-names-in-kit-pages/valid/+test-for-form-input.svelte

  fix: false positives for `form` in `svelte/valid-prop-names-in-kit-pages`

---

.changeset/sharp-beans-design.md
docs-svelte-kit/src/lib/components/ESLintCodeBlock.svelte
docs-svelte-kit/src/lib/components/ESLintPlayground.svelte
src/shared/svelte-compile-warns/transform/babel.ts
src/shared/svelte-compile-warns/transform/less.ts
src/shared/svelte-compile-warns/transform/sass.ts
src/shared/svelte-compile-warns/transform/stylus.ts
src/shared/svelte-compile-warns/transform/typescript.ts
src/types.ts
src/utils/load-module.ts
src/utils/ts-utils/index.ts

This PR improves the way external modules are loaded.
The vscode extention doesn't seem to get the cwd location to work well out of the box when using workspaces.
We could work around this by setting `eslint.workingDirectories` , but perhaps it would be easier for users to improve the way they are loaded by the plugin.
---
close #343

fix: improved loading of external modules

---

.changeset/witty-donuts-jog.md
README.md
docs/rules.md
docs/rules/require-event-dispatcher-types.md
src/rules/reference-helpers/svelte-createEventDispatcher.ts
src/rules/require-event-dispatcher-types.ts
src/utils/rules.ts
tests/fixtures/rules/require-event-dispatcher-types/invalid/import-alias01-errors.yaml
tests/fixtures/rules/require-event-dispatcher-types/invalid/import-alias01-input.svelte
tests/fixtures/rules/require-event-dispatcher-types/invalid/no-types01-errors.yaml
tests/fixtures/rules/require-event-dispatcher-types/invalid/no-types01-input.svelte
tests/fixtures/rules/require-event-dispatcher-types/valid/has-types01-input.svelte
tests/fixtures/rules/require-event-dispatcher-types/valid/no-typescript01-input.svelte
tests/fixtures/rules/require-event-dispatcher-types/valid/non-svelte-dispatcher01-input.svelte
tests/src/rules/require-event-dispatcher-types.ts

Added the `require-event-dispatcher-types` rule

---

.changeset/honest-garlics-march.md
src/shared/svelte-compile-warns/index.ts
src/shared/svelte-compile-warns/transform/babel.ts
src/shared/svelte-compile-warns/transform/less.ts
src/shared/svelte-compile-warns/transform/postcss.ts
src/shared/svelte-compile-warns/transform/sass.ts
src/shared/svelte-compile-warns/transform/stylus.ts
src/shared/svelte-compile-warns/transform/typescript.ts
tests/fixtures/rules/no-unused-svelte-ignore/valid/ts-lang01-input.svelte
tests/fixtures/rules/valid-compile/valid/ts/ts-lang01-input.svelte

fix: false positives for ts in `svelte/no-unused-svelte-ignore`

---

.changeset/yellow-games-double.md
docs/rules/valid-prop-names-in-kit-pages.md
src/rules/valid-prop-names-in-kit-pages.ts
tests/fixtures/rules/valid-prop-names-in-kit-pages/valid/+test001-input.svelte

Recently, SvelteKit added snapshot feature.
https://kit.svelte.dev/docs/snapshots

[feat] Support `snapshot` to `valid-prop-names-in-kit-pages` rule

---

.changeset/many-cougars-act.md
src/shared/svelte-compile-warns/transform/typescript.ts

Suggestion for https://github.com/ota-meshi/eslint-plugin-svelte/issues/374

Allow to specify TS target using parserOptions

---

.changeset/grumpy-gifts-repeat.md
src/rules/no-dom-manipulating.ts
tests/fixtures/rules/no-dom-manipulating/valid/read-prop01-input.svelte
tests/fixtures/rules/no-dom-manipulating/valid/read-prop02-input.svelte

fix: false positives for read property in `svelte/no-dom-manipulating`

---

lint-staged.config.js

This PR changes the configuration of lint-staged.
The new configuration excludes typescript validation. Because it to take long. It is also done in CI so it is not always necessary.

chore: change lint-staged config

---

.changeset/wet-books-travel.md
src/rules/infinite-reactive-loop.ts
src/rules/reference-helpers/svelte-store.ts
src/rules/require-event-dispatcher-types.ts

We were passing `context.getScope()` to the ReferenceTracker's constructor, which was not always correct, because the ReferenceTracker's constructor requires a Global scope.
Fix this PR to always pass a Global scope instance.
Without this change, https://github.com/ota-meshi/svelte-eslint-parser/pull/292 now returns the correct scopes, so the rules will not work properly.

fix: `ReferenceTracker` usage

---

.changeset/all-config.md
README.md
docs/user-guide.md
src/configs/all.ts
src/index.ts

`all` config

---

docs/rules/experimental-require-slot-types.md

this example was incorrectly in a javascript `script` block when it uses typescript syntax:

fix syntax error in experimental-require-slot-types example

---

.changeset/pretty-emus-hammer.md
src/rules/infinite-reactive-loop.ts
tests/fixtures/rules/infinite-reactive-loop/valid/recursive-reference-input.svelte

fix: maximum call stack error in `svelte/infinite-reactive-loop` rule

---

.changeset/heavy-cycles-explain.md
src/shared/svelte-compile-warns/extract-leading-comments.ts
src/shared/svelte-compile-warns/index.ts
tests/fixtures/rules/no-unused-svelte-ignore/invalid/invalid-svelte-ignore01-errors.yaml
tests/fixtures/rules/no-unused-svelte-ignore/invalid/invalid-svelte-ignore01-input.svelte
tests/fixtures/rules/no-unused-svelte-ignore/invalid/invalid-svelte-ignore02-errors.yaml
tests/fixtures/rules/no-unused-svelte-ignore/invalid/invalid-svelte-ignore02-input.svelte
tests/fixtures/rules/no-unused-svelte-ignore/invalid/invalid-svelte-ignore03-errors.yaml
tests/fixtures/rules/no-unused-svelte-ignore/invalid/invalid-svelte-ignore03-input.svelte
tests/fixtures/rules/no-unused-svelte-ignore/valid/svelte-ignore01-input.svelte
tests/fixtures/rules/no-unused-svelte-ignore/valid/svelte-ignore02-input.svelte
tests/fixtures/rules/no-unused-svelte-ignore/valid/svelte-ignore03-input.svelte
tests/fixtures/rules/no-unused-svelte-ignore/valid/svelte-ignore04-input.svelte
tests/fixtures/rules/no-unused-svelte-ignore/valid/svelte-ignore05-input.svelte
tests/fixtures/rules/no-unused-svelte-ignore/valid/svelte-ignore06-input.svelte
tests/fixtures/rules/no-unused-svelte-ignore/valid/svelte-ignore07-input.svelte
tests/fixtures/rules/valid-compile/invalid/invalid-svelte-ignore01-errors.yaml
tests/fixtures/rules/valid-compile/invalid/invalid-svelte-ignore01-input.svelte
tests/fixtures/rules/valid-compile/invalid/invalid-svelte-ignore02-errors.yaml
tests/fixtures/rules/valid-compile/invalid/invalid-svelte-ignore02-input.svelte
tests/fixtures/rules/valid-compile/invalid/invalid-svelte-ignore03-errors.yaml
tests/fixtures/rules/valid-compile/invalid/invalid-svelte-ignore03-input.svelte
tests/fixtures/rules/valid-compile/valid/svelte-ignore01-input.svelte
tests/fixtures/rules/valid-compile/valid/svelte-ignore02-input.svelte
tests/fixtures/rules/valid-compile/valid/svelte-ignore03-input.svelte
tests/fixtures/rules/valid-compile/valid/svelte-ignore04-input.svelte
tests/fixtures/rules/valid-compile/valid/svelte-ignore05-input.svelte
tests/fixtures/rules/valid-compile/valid/svelte-ignore06-input.svelte
tests/fixtures/rules/valid-compile/valid/svelte-ignore07-input.svelte
typings/estree/index.d.ts

fix: false positive for containing element in `svelte/no-unused-svelte-ignore`

---

README.md
docs/user-guide.md

The TypeScript parser uses a singleton internally, which means that repeated `parserOptions` will be ignored, using only the first one. This can lead to unexpected behaviour if there are multiple possible configurations.
This closes #422.
Ref: #422

docs: warn about the typescript parser being a singleton

---

docs/migration.md

This PR fixes migration.md.
The link to `README.md#why` is gone, so I changed it to direct to another link in this PR change.

chore: fix migration.md

---

.changeset/curvy-bananas-pretend.md
README.md
docs/rules.md
docs/rules/no-immutable-reactive-statements.md
src/rules/no-immutable-reactive-statements.ts
src/utils/rules.ts
tests/fixtures/rules/no-immutable-reactive-statements/invalid/immutable-let-errors.yaml
tests/fixtures/rules/no-immutable-reactive-statements/invalid/immutable-let-input.svelte
tests/fixtures/rules/no-immutable-reactive-statements/invalid/immutable01-errors.yaml
tests/fixtures/rules/no-immutable-reactive-statements/invalid/immutable01-input.svelte
tests/fixtures/rules/no-immutable-reactive-statements/invalid/readonly-export01-errors.yaml
tests/fixtures/rules/no-immutable-reactive-statements/invalid/readonly-export01-input.svelte
tests/fixtures/rules/no-immutable-reactive-statements/valid/mutable01-input.svelte
tests/fixtures/rules/no-immutable-reactive-statements/valid/unknown01-input.svelte
tests/src/rules/no-immutable-reactive-statements.ts
tests/utils/utils.ts

This PR adds `svelte/no-immutable-reactive-statements` rule that reports if all variables referenced in reactive statements are immutable.
close #382

feat: add `svelte/no-immutable-reactive-statements` rule

---

.github/workflows/NodeCI.yml

Svelte 4 branch also added CI with Node 20. So I added it to this repo also.

chore: add Node 20 in CI

---

.eslintrc.js

This PR introduces `@typescript-eslint/no-restricted-imports`.
I have introduced #450 bugs in the past. I found a way to prevent this in the future by using `@typescript-eslint/no-restricted-imports`.
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-restricted-imports.md

chore: introducing `@typescript-eslint/no-restricted-imports`

---

.changeset/gorgeous-geckos-unite.md
src/rules/prefer-destructured-store-props.ts
tests/fixtures/rules/prefer-destructured-store-props/valid/builtin-vars01-input.svelte
tests/fixtures/rules/prefer-destructured-store-props/valid/builtin-vars02-input.svelte

fix: false positives for builtin `$$` vars in `svelte/prefer-destructured-store-props`

---

.changeset/gentle-doors-impress.md
README.md
docs/rules.md
docs/rules/require-each-key.md
src/rules/require-each-key.ts
src/utils/rules.ts
tests/fixtures/rules/require-each-key/invalid/each-block-without-key01-errors.yaml
tests/fixtures/rules/require-each-key/invalid/each-block-without-key01-input.svelte
tests/fixtures/rules/require-each-key/valid/keyed-each-block01-input.svelte
tests/src/rules/require-each-key.ts

feat: add `svelte/require-each-key` rule

---

.changeset/shy-moles-deliver.md
README.md
docs/rules.md
docs/rules/require-each-key.md
docs/rules/valid-each-key.md
src/rules/valid-each-key.ts
src/utils/rules.ts
tests/fixtures/rules/.eslintrc.js
tests/fixtures/rules/valid-each-key/invalid/const-key01-errors.yaml
tests/fixtures/rules/valid-each-key/invalid/const-key01-input.svelte
tests/fixtures/rules/valid-each-key/invalid/out-vars-key01-errors.yaml
tests/fixtures/rules/valid-each-key/invalid/out-vars-key01-input.svelte
tests/fixtures/rules/valid-each-key/valid/call-key01-input.svelte
tests/fixtures/rules/valid-each-key/valid/destructure-key01-input.svelte
tests/fixtures/rules/valid-each-key/valid/expression-key01-input.svelte
tests/fixtures/rules/valid-each-key/valid/expression-key02-input.svelte
tests/fixtures/rules/valid-each-key/valid/index-key01-input.svelte
tests/fixtures/rules/valid-each-key/valid/member-key01-input.svelte
tests/src/rules/valid-each-key.ts

See https://github.com/sveltejs/eslint-plugin-svelte/pull/473#pullrequestreview-1418940020

feat: add `svelte/valid-each-key` rule

---

.changeset/friendly-toys-end.md
.changeset/grumpy-gorillas-sip.md
.eslintrc.js
.github/workflows/NodeCI.yml
docs-svelte-kit/src/lib/header/Header.svelte
docs-svelte-kit/src/routes/+layout.svelte
package.json

feat: add experimental support for Svelte v4

---

.eslintrc.js
tools/render-rules.ts
tools/update-docs.ts

In my experience in this repository, I felt that in most cases I have to write comments what is known by the function name too, so I thought it would be okay to remove this rule.

chore: remove `require-jsdoc` internal rule

---

.changeset/tasty-flies-love.md
src/rules/no-unused-class-name.ts
tests/fixtures/rules/no-unused-class-name/valid/test-input.js

fix: crash with non svelte files in `svelte/no-unused-class-name`

---

.changeset/beige-jobs-travel.md
docs/rules/no-unused-class-name.md
src/rules/no-unused-class-name.ts
tests/fixtures/rules/no-unused-class-name/invalid/allowed-class-names/_config.json
tests/fixtures/rules/no-unused-class-name/invalid/allowed-class-names/partially-allowed-class-name01-errors.yaml
tests/fixtures/rules/no-unused-class-name/invalid/allowed-class-names/partially-allowed-class-name01-input.svelte
tests/fixtures/rules/no-unused-class-name/valid/allowed-class-names/_config.json
tests/fixtures/rules/no-unused-class-name/valid/allowed-class-names/allowed-class-name01-input.svelte

feat(no-unused-class-name): added a whitelist option

---

.changeset/light-boats-press.md
src/rules/experimental-require-slot-types.ts
src/rules/experimental-require-strict-events.ts
tests/fixtures/rules/experimental-require-slot-types/valid/has-slot-types-with-alias01-input.svelte
tests/fixtures/rules/experimental-require-strict-events/valid/has-events-type-alias01-input.svelte

Hello 👋
Currently these two rules `experimental-require-strict-events`, `experimental-require-slot-types` which assert existence of $$Slots/$$Events handles interface declarations only. However, Svelte Language Server works with type aliases as well. I added an option that will catch them when they're declared as type aliases. I also added failing tests, before implementing fixes. 
I'm also wondering whether the wording e.g. `The component must define the $$Slots interface` should be adjusted? 
Closes #528

fix: handle type aliases for $$Slots and $$Events related rules

---

.changeset/hip-donkeys-collect.md
.prettierignore
src/rules/no-immutable-reactive-statements.ts
tests/fixtures/rules/no-immutable-reactive-statements/valid/mutable-member-input.svelte

fix: false positives for mutable member in `svelte/no-immutable-reactive-statements` rule

---

.changeset/small-fishes-sin.md
src/rules/indent-helpers/es.ts
src/rules/indent-helpers/ts.ts
src/rules/require-event-dispatcher-types.ts

This PR replaces the deprecated typeParameters with typeArguments.
It appears that some node typeParameters have been deprecated. But to support older parsers, we want to use typeParameters if typeArguments doesn't exist.

fix: replace deprecated typeParameters with typeArguments

---

docs/rules/no-target-blank.md

The behavior of `allowReferrer` was very confusing to me because I thought it was referring to the `rel` attribute and I did not understand it's actually referring to the `Referer` header being allowed
I was also very confused about the security vulnerability being referred to. I assumed it was related to protecting the user's privacy by not passing the referrer header. When I happened to click the reference link I saw that I had been misunderstanding the purpose of this rule and what exactly it was doing.

docs: clarify docs for `svelte/no-target-blank`

---

.changeset/lazy-dancers-vanish.md
package.json

Use the latest Svelte 5 compatible parser.
Should we increase the minor version for this change?

feat: Follow latest Svelte 5

---

eslint.config.mjs

I have no idea how to fix below lint errors.
https://github.com/sveltejs/eslint-plugin-svelte/actions/runs/8978756715/job/24659835714
So I just disable rules.

fix: disable a few rules in docs-svelte-kit

---

.changeset/ninety-lobsters-dress.md
packages/eslint-plugin-svelte/src/shared/svelte-compile-warns/transform/typescript.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-compile/valid/ts/ts-unused-in-script-input.svelte

close #652
This PR fixes the issue mentioned in the comments below.
https://github.com/sveltejs/eslint-plugin-svelte/issues/652#issuecomment-2087008855
In the code posted at the top of the thread the rule seems to work correctly, and correctly shows the svelte compiler warnings.

fix: false positives for import vars with TS in `svelte/valid-compile`

---

.changeset/silent-lamps-chew.md
.changeset/silent-lamps-chew2.md
README.md
docs/user-guide.md
packages/eslint-plugin-svelte/src/rules/no-unused-class-name.ts
packages/eslint-plugin-svelte/src/types.ts
packages/eslint-plugin-svelte/src/utils/svelte-kit.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-export-load-in-svelte-module-in-kit-pages/invalid/svelte-config-from-parser-options/+test01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/no-export-load-in-svelte-module-in-kit-pages/invalid/svelte-config-from-parser-options/+test01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-export-load-in-svelte-module-in-kit-pages/invalid/svelte-config-from-parser-options/_config.json
packages/eslint-plugin-svelte/tests/fixtures/rules/no-export-load-in-svelte-module-in-kit-pages/invalid/svelte-config/+test01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/no-export-load-in-svelte-module-in-kit-pages/invalid/svelte-config/+test01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-export-load-in-svelte-module-in-kit-pages/invalid/svelte-config/svelte.config.js
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-prop-names-in-kit-pages/invalid/svelte-config-from-parser-options/+test001-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-prop-names-in-kit-pages/invalid/svelte-config-from-parser-options/+test001-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-prop-names-in-kit-pages/invalid/svelte-config-from-parser-options/_config.json
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-prop-names-in-kit-pages/invalid/svelte-config/+test001-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-prop-names-in-kit-pages/invalid/svelte-config/+test001-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-prop-names-in-kit-pages/invalid/svelte-config/svelte.config.js

This PR improves the two rules to use `svelte.config.js` data provided by the parser.
- `svelte/valid-prop-names-in-kit-pages`
- `svelte/no-export-load-in-svelte-module-in-kit-pages`

feat: improve `svelte/valid-prop-names-in-kit-pages` and `svelte/no-export-load-in-svelte-module-in-kit-pages` to use `svelte.config.js` data

---

.changeset/tough-jobs-rest.md
packages/eslint-plugin-svelte/src/shared/svelte-compile-warns/transform/typescript.ts

See comment https://github.com/sveltejs/eslint-plugin-svelte/pull/790#discussion_r1642834898

fix: `svelte/valid-compile` to use verbatimModuleSyntax to work with TS v5.5.

---

.changeset/nervous-rings-applaud.md
packages/eslint-plugin-svelte/src/rules/indent-helpers/svelte.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/indent/invalid/snippets01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/indent/invalid/snippets01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/indent/invalid/snippets01-output.svelte

Fix `svelte/indent` rule for `SvelteSnippetBlock`, by ensuring that the children and closing tags are properly indented.
Closes #863.

fix(svelte/indent): ensure proper snippet indent

---

.changeset/warm-eyes-boil.md
docs-svelte-kit/eslint.config.mjs
docs-svelte-kit/src/lib/eslint/scripts/linter.js
packages/eslint-plugin-svelte/eslint.config.mjs
packages/eslint-plugin-svelte/src/configs/flat/all.ts

This type has been deprecated in eslint, see https://github.com/eslint/eslint/blob/71f37c5bf04afb704232d312cc6c72c957d1c14e/lib/types/index.d.ts#L1306

chore: Avoid using deprecated FlatConfig eslint type

---

packages/eslint-plugin-svelte/tools/new-rule.ts

Current `new-rule.ts` script generates a doc inside the
`./packages/eslint-plugin-svelte`, instead of creating a doc in the actual
`./docs` folder.

fix: correct new rule docs path

---

packages/eslint-plugin-svelte/tools/new-rule.ts

Add optional command `--code` to the `new` command to generate a new rule. Added
a very simple logic to detect the argument `--code`.
`--code` is an optional boolean argument that defaults to `false`
Closes #607.

fix: optional param to open new files with `code`

---

docs/rules/html-closing-bracket-new-line.md

Correcting:
- [Comment 1](https://github.com/sveltejs/eslint-plugin-svelte/pull/870#discussion_r1841785961)
- [Comment 2](https://github.com/sveltejs/eslint-plugin-svelte/pull/870#discussion_r1841786863)
Thanks to @noy4 for pointing the issues out.

fix: correct `svelte/html-closing-bracket-new-line` docs

---

.changeset/violet-cobras-tap.md
package.json

chore: downgraded eslint to 9.14 to prevent incompatibility with typescript-eslint

---

.changeset/fast-coins-fly.md
packages/eslint-plugin-svelte/package.json

feat: support `<svelte:boundary>`

---

packages/eslint-plugin-svelte/tools/new-rule.ts

After migrate the repo to ESM, `tools/new-rule.ts` doesn't work due to `ReferenceError: __dirname is not defined`.

chore: fix `tools/new-rule.ts`

---

.changeset/itchy-dragons-boil.md
packages/eslint-plugin-svelte/package.json
packages/eslint-plugin-svelte/src/rules/no-unused-class-name.ts
packages/eslint-plugin-svelte/src/types.ts

Changes based on sveltejs/svelte-eslint-parser#619

chore: using svelte-eslint-parser for style selector parsing

---

.github/workflows/NodeCI.yml

We support ESLint >= `8.57.0`, therefore, we don't need to test with `typescript-eslint` < 8.
Because `typescript-eslint` v7 supports ESLint >= 8.56.0. (`eslint-plugin-svelte` doesn't support ESLint `8.56.0`)
https://github.com/typescript-eslint/typescript-eslint/blob/v7.18.0/packages/eslint-plugin/package.json#L101

chore: remove `typescript-eslint` v5 test

---

packages/eslint-plugin-svelte/src/rules/no-unused-class-name.ts
packages/eslint-plugin-svelte/src/types.ts

I think all properties should be optional because the functions that exist depend on which parser is used.

chore: make properties in `parserServices` optional

---

.changeset/two-students-pump.md
packages/eslint-plugin-svelte/src/utils/svelte-context.ts

This PR addresses a bug in the method for extracting the library’s major version. While it does not support all possible version specification methods, I believe it is sufficient for extracting the major version of Svelte and SvelteKit.
This bug is introduced in https://github.com/sveltejs/eslint-plugin-svelte/pull/980.

fix: update method for extracting major version

---

.changeset/perfect-mirrors-doubt.md
packages/eslint-plugin-svelte/src/rules/no-reactive-reassign.ts

The Svelte 5 compiler throws an error if a `$derived` value is reassigned. For object values, it’s better to use `const` instead of `let`. This will be addressed by https://github.com/sveltejs/eslint-plugin-svelte/pull/985
```svelte
<script>
let count = $state(1);
let double = $derived(count * 2);
let obj = $state({ foo: 1 });
let derivedObj = $derived( { ...obj, bar: true });
function invalid() {
double = double + 1;
derivedObj.bar = false;
}
</script>
```
https://svelte.dev/playground/hello-world?version=5.17.3#H4sIAAAAAAAAE22PwU7EMAxEf8WyOLRQBZVjdheJGzc-gHBIGlfKKptUiVtAVf8dZdstHLhZM2_G9oxBXwglvpL3ET5j8hYqso7J1thg7zxllO8z8vdQuCJgc0u9DIPIE3kumtGZ_tO7GJgCZ5R4zF1yAz-rAOCJoYtjYDjBXWbNVLX1QQXFxbFxNJ6KZSm5iWy1svfwdIU2LJrzb3yGPkYJLSx_etb028rdumAGIUQ05waMThI4jbSlguJ-DB27GMCFSXtnqxrmoiver9qGB2gPm …

chore: do not run `no-reactive-reassign` rule on Svelte 5 with runes

---

docs-svelte-kit/package.json
docs-svelte-kit/src/site.css
docs-svelte-kit/tools/vite-plugin-svelte-md-option.mts
docs/rules/no-export-load-in-svelte-module-in-kit-pages.md
docs/rules/no-inner-declarations.md
docs/rules/valid-prop-names-in-kit-pages.md

chore: fix some broken examples on docs site

---

.changeset/old-numbers-pull.md
packages/eslint-plugin-svelte/src/rules/no-useless-mustaches.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-useless-mustaches/valid/valid-test02-input.svelte

close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1036

fix: account for \n and \r in `TemplateLiteral` handling for the `no-useless-mustaches` rule

---

.github/workflows/GHPages.yml
.github/workflows/pkg.pr.new.yml

Restrict some GH actions to not run on forks

---

.github/workflows/pkg.pr.new-comment.yml
.github/workflows/pkg.pr.new.yml

This PR changes the workflow of pkg.pr.new.
The workflow of #1054 is failing with 403 error.
I expect that by splitting the workflow in this PR based on the svelte repository, we can avoid the 403 error.

chore: update pkg.pr.new workflow

---

.changeset/stupid-penguins-smoke.md
README.md
docs/rules.md
docs/rules/valid-style-parse.md
packages/eslint-plugin-svelte/src/rule-types.ts
packages/eslint-plugin-svelte/src/rules/valid-style-parse.ts
packages/eslint-plugin-svelte/src/utils/rules.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-style-parse/invalid/invalid-css01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-style-parse/invalid/invalid-css01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-style-parse/invalid/invalid-scss01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-style-parse/invalid/invalid-scss01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-style-parse/invalid/unknown-lang01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-style-parse/invalid/unknown-lang01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-style-parse/valid/no-style01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-style-parse/valid/valid-css01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-style-parse/valid/valid-scss01-input.svelte
packages/eslint-plugin-svelte/tests/src/rules/valid-style-parse.ts

feat: implemented the `valid-style-parse` rule

---

.changeset/two-poets-wait.md
packages/eslint-plugin-svelte/src/rules/valid-prop-names-in-kit-pages.ts
packages/eslint-plugin-svelte/src/utils/get-node-module.ts
packages/eslint-plugin-svelte/src/utils/svelte-context.ts

I noticed this issue while using pnpm catalog in our project.

feat: detect version information from `node_modules` for pnpm’s catalog

---

README.md

As discussed in https://github.com/sveltejs/eslint-plugin-svelte/commit/083ea48dfac10c3c084f830c758c3d6249bc8a68#r153008818
> According to ESLint’s versioning rules, new rules are not added to the recommended config in minor releases. This means users will not encounter new lint errors when upgrading minor/patch versions.
>
> However, eslint-plugin-svelte v3 does not follow this rule.
The README link in the [v3.0.0 release](https://github.com/sveltejs/eslint-plugin-svelte/releases/tag/eslint-plugin-svelte%403.0.0) should probably be updated as well.
```diff
- https://github.com/sveltejs/eslint-plugin-svelte/blob/eslint-plugin-svelte%403.0.0/README.md#versioning-policy
+ https://github.com/sveltejs/eslint-plugin-svelte/blob/eslint-plugin-svelte%403.0.2/README.md#versioning-policy
```

docs: clarify versioning policy

---

docs/rules/require-each-key.md

The current further reading link result in 404 because the tutorial link now has svelte or kit in the url

Docs: Update require-each-key further reading link

---

.changeset/angry-books-go.md
packages/eslint-plugin-svelte/package.json

close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1114
⚠️ We need to release https://github.com/sveltejs/svelte-eslint-parser/pull/681 first.

fix: align required Node version with ESLint

---

.changeset/sixty-cars-fail.md
docs/rules/prefer-const.md
packages/eslint-plugin-svelte/src/rule-types.ts
packages/eslint-plugin-svelte/src/rules/prefer-const.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/invalid/option1/_config.json
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/invalid/option1/test01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/invalid/option1/test01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/invalid/option1/test01-output.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/invalid/option2/_config.json
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/invalid/option2/test01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/invalid/option2/test01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/invalid/option2/test01-output.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/invalid/test01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/invalid/test01-output.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/valid/option1/_config.json
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/valid/option1/test01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/valid/option2/_config.json
packages/eslint-plugin-svelte/tests/fixtures/rules/prefer-const/valid/option2/test01-input.svelte

close part of https://github.com/sveltejs/eslint-plugin-svelte/issues/818
As explained here, `$state` also needs to be excluded from the `prefer-const` rule.
https://github.com/sveltejs/eslint-plugin-svelte/pull/985#issuecomment-2566907151

feat: add `excludedRunes` option to the `prefer-const` rule

---

.changeset/warm-plums-smile.md
packages/eslint-plugin-svelte/src/rules/no-navigation-without-base.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-base/invalid/link-with-fragment01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-base/invalid/link-with-fragment01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-base/valid/link-fragment-url01-input.svelte

fix(no-navigation-without-base): ignoring fragment links

---

.changeset/purple-months-report.md
packages/eslint-plugin-svelte/src/rules/consistent-selector-style.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/consistent-selector-style/valid/id-class-type/class01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/consistent-selector-style/valid/id-type-class/class01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/consistent-selector-style/valid/type-class-id/class01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/consistent-selector-style/valid/type-id-class/class01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/consistent-selector-style/valid/type-id/class01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/consistent-selector-style/valid/type/class01-input.svelte

fix(consistent-selector-style): not reporting class selectors used in class directives

---

.changeset/fuzzy-ads-join.md
packages/eslint-plugin-svelte/src/rules/no-unused-props.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/ts-basic-input.svelte

close: https://github.com/sveltejs/eslint-plugin-svelte/pull/1061#issuecomment-2728592702
close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1028#issuecomment-2728101827

fix: resolve false positives on nested objects in `no-unused-props` rule

---

.changeset/plain-chairs-tie.md
packages/eslint-plugin-svelte/src/rules/no-unused-props.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/invalid/ignore-external-type-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/invalid/ignore-external-type-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/invalid/imported-type-check-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/invalid/shared-types.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/ignore-external-type-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/shared-types.ts

close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1133
close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1136

fix: correct detection of externally defined types in `no-unused-props` rule

---

.changeset/floppy-symbols-sing.md
packages/eslint-plugin-svelte/src/rules/no-unused-props.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/nested-props2-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/nested-props3-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/nested-props4-input.svelte

close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1142

fix: stop reporting child properties in `no-unused-props` when the parent object itself is used

---

.changeset/few-singers-marry.md
packages/eslint-plugin-svelte/src/rules/no-unused-props.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/bindable-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/default-value-input.svelte

close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1145

fix(no-unused-props): resolve false positives on props with default values or $bindable usage

---

packages/eslint-plugin-svelte/tests/utils/utils.ts

Currently, we assume test output will always be a `.svelte` file. This isn't always true (e.g. for the derived input/output rule).
This changes the util to basically use the extension of the input in the output, and avoids re-computing it by passing it in.

test: account for js output in test cases

---

packages/eslint-plugin-svelte/src/rules/no-unused-props.ts

This is just the refactoring PR.

chore: rename variable names in `no-unused-props`

---

packages/eslint-plugin-svelte/package.json
packages/eslint-plugin-svelte/tests/utils/eslint-compat.ts

We no longer use it in production code, only in tests. So we can move this to `devDependencies` now.

chore: move compat dependency to devDependencies

---

docs/rules/no-at-html-tags.md
docs/rules/prefer-class-directive.md
docs/rules/require-each-key.md
docs/rules/valid-each-key.md

These currently lead to 404s. Updating links as well as described paths to match current tutorial

docs: update valid-each-key, require-each-key, no-at-html-tags, prefer-class-directive further reading links

---

.changeset/dry-facts-eat.md
docs-svelte-kit/package.json
packages/eslint-plugin-svelte/package.json
packages/eslint-plugin-svelte/src/meta.ts
packages/eslint-plugin-svelte/src/utils/ast-utils.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/sort-attributes/invalid/attach-tag-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/sort-attributes/invalid/attach-tag-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/sort-attributes/invalid/attach-tag-output.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/sort-attributes/valid/attach-tag-input.svelte

close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1220

feat(sort-attributes): support `{@attach}`

---

.changeset/happy-weeks-argue.md
packages/eslint-plugin-svelte/src/rules/no-top-level-browser-globals.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-top-level-browser-globals/valid/ts01-input.svelte

fix(no-top-level-browser-globals): false positives for type annotations

---

.changeset/fast-bottles-allow.md
.changeset/forty-signs-smoke.md
docs/rules/no-unused-class-name.md
packages/eslint-plugin-svelte/src/rules/no-unused-class-name.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-class-name/invalid/allowed-class-names/_config.json
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-class-name/invalid/allowed-class-names/partially-allowed-class-name01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-class-name/invalid/allowed-class-names/partially-allowed-class-name01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-class-name/valid/allowed-class-names/_config.json
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-class-name/valid/allowed-class-names/allowed-class-name01-input.svelte

When I use this rule for project which is using `unocss`, I want to add unocss's [dynamic-rules](https://unocss.dev/config/rules#dynamic-rules) to `allowedClassNames`
ex) `/^m-(\d+)$/`

feat(no-unused-class-name): Support Regex for `allowedClassNames` option

---

.changeset/dry-colts-open.md
packages/eslint-plugin-svelte/src/rules/no-unused-class-name.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-class-name/invalid/duplicated-class-name-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-class-name/invalid/duplicated-class-name-input.svelte

close https://github.com/sveltejs/eslint-plugin-svelte/issues/1259

fix(no-unused-class-name): detect duplicated class names

---

.changeset/six-pugs-camp.md
packages/eslint-plugin-svelte/src/rules/no-goto-without-base.ts
packages/eslint-plugin-svelte/src/rules/no-navigation-without-base.ts
packages/eslint-plugin-svelte/src/rules/no-navigation-without-resolve.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-goto-without-base/invalid/no-base01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/no-goto-without-base/invalid/no-base01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-goto-without-base/valid/absolute-uri01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-base/invalid/link-no-base01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-base/invalid/link-no-base01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-base/invalid/link-with-fragment01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-base/invalid/link-with-fragment01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-base/valid/link-absolute-url01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-base/valid/link-fragment-url01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-resolve/invalid/link-with-fragment01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-resolve/invalid/link-with-fragment01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-resolve/invalid/link-without-resolve01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-resolve/invalid/link-without-resolve01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-resolve/valid/link-absolute-url01-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-navigation-without-resolve/valid/link-fragment-url01-input.svelte

fix: Not reporting mailto: and other unusual schema addresses in no-nmavigation-without-resolve (and its deprecated versions)

---

docs/rules/no-navigation-without-base.md
docs/rules/no-navigation-without-resolve.md

In docs for navigation lint rules.

Fix spelling of 'internal' and 'function'

---

.github/workflows/Release.yml

and align permissions setup with other svelte org release.yml to enable oidc publishing

refactor(release): use node24, remove NPM_TOKEN 

---

package.json
packages/eslint-plugin-svelte/package.json

I'm trying to fix release action.
https://github.com/sveltejs/eslint-plugin-svelte/actions/runs/17599926478/job/49999938393
I still haven’t figured out the cause of the failures, but I’m going through the configuration differences with the Svelte repository one by one.

chore: align `repository` field with svelte repo

---

.github/workflows/Release.yml

I don't think we need this but I can not find any other reason why the release is failed...

chore: try to update npm for release action

---

.changeset/icy-rocks-camp.md
.gitattributes
.github/workflows/NodeCI.yml
.vscode/settings.json
packages/eslint-plugin-svelte/src/rules/no-unused-props.ts
packages/eslint-plugin-svelte/src/rules/valid-style-parse.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-style-parse/invalid/invalid-css01-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/valid-style-parse/invalid/invalid-scss01-errors.yaml
packages/eslint-plugin-svelte/tests/src/rules/@typescript-eslint/original-tests/no-unnecessary-condition.ts
packages/eslint-plugin-svelte/tests/utils/utils.ts
packages/eslint-plugin-svelte/tools/lib/changesets-util.ts
packages/eslint-plugin-svelte/tools/lib/load-rules.ts
packages/eslint-plugin-svelte/tools/lib/write.ts
packages/eslint-plugin-svelte/tools/new-rule.ts
packages/eslint-plugin-svelte/tools/update-docs-rules-index.ts
packages/eslint-plugin-svelte/tools/update-docs.ts
packages/eslint-plugin-svelte/tools/update-meta.ts
packages/eslint-plugin-svelte/tools/update-readme.ts
packages/eslint-plugin-svelte/tools/update-rule-types.ts
packages/eslint-plugin-svelte/tools/update-rules.ts
packages/eslint-plugin-svelte/tools/update-rulesets.ts
packages/eslint-plugin-svelte/tools/update-types-for-node.ts
prettier.config.cjs

This PR adds support for Windows environments.
It:
- Forces `\n` as the end-of-line character
- Normalizes paths whenever possible to stay cross-platform
- Enables Windows runners in NodeCI
closes #1335

feat: add windows support

---

README.md
docs/user-guide.md

close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1264
close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1293

chore: update README regarding `svelteConfig`

---

.changeset/real-books-stare.md
packages/eslint-plugin-svelte/src/rules/no-unused-props.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/spread-nested1-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/spread-nested2-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/spread-nested3-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/spread-nested4-config.json
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/spread-nested4-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/spread-nested5-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/spread-root1-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/spread-root2-config.json
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/spread-root2-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unused-props/valid/spread-root3-input.svelte

close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1369
I’m not entirely satisfied with this fix, but making the code better would take quite a bit more time, so I’m submitting the PR as-is for now.

fix(no-unused-props): validate spread operator properly
