sveltejs/eslint-plugin-svelte

README.md
docs/user-guide/README.md

Add parser config docs.

---

README.md
docs/user-guide/README.md

Add to docs how to use it with `@typescript-eslint/parser`.

---

package.json

Use eslint-plugin-svelte v2 for dogfooding.

Use eslint-plugin-svelte v2

---

src/rules/prefer-style-directive.ts
tests/fixtures/rules/prefer-style-directive/invalid/svelte-element01-errors.json
tests/fixtures/rules/prefer-style-directive/invalid/svelte-element01-input.svelte
tests/fixtures/rules/prefer-style-directive/invalid/svelte-element01-output.svelte
tests/fixtures/rules/prefer-style-directive/valid/ignore-component01-input.svelte
tests/fixtures/rules/prefer-style-directive/valid/ignore-svelte-self01-input.svelte

Fix false positives for component in `prefer-style-directive` rule

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/new_rule_request.yml
.github/ISSUE_TEMPLATE/other.md

This PR introduces the issue templates, to show users some guidance.

Add issue template

---

.github/workflows/NodeCI.yml

See https://github.com/ota-meshi/eslint-plugin-svelte/pull/259#issuecomment-1256079261

chore: fix ci

---

README.md
docs/user-guide.md

Following up on the discussion in #258.

More explicit docs for what the prettier config does

---

.changeset/chilly-olives-check.md
.github/workflows/NodeCI.yml
src/rules/system.ts
tests/src/settings/ignore-warnings.ts

fix: false report in `settings.ignoreWarnings`

---

package.json

related to https://github.com/ota-meshi/eslint-plugin-svelte/pull/281#discussion_r1008856805

chore: update eslint-plugin-svelte to v2.11.0

---

.changeset/orange-impalas-speak.md
package.json
src/utils/get-package-json.ts
src/utils/svelte-kit.ts
tests/fixtures/rules/sort-attributes/.eslintrc.js

fix: update svelte-eslint-parser to v0.23

---

tests/fixtures/rules/tsconfig.json
tests/utils/utils.ts

chore: support ts test fixtures

---

.changeset/rotten-camels-count.md
package.json

feat: update svelte-eslint-parser to v0.25

---

.changeset/great-hornets-fold.md
src/rules/no-reactive-reassign.ts

fix: broken import when not using typescript-eslint

---

.changeset/empty-badgers-learn.md
src/rules/no-immutable-reactive-statements.ts
tests/fixtures/rules/no-immutable-reactive-statements/valid/builtin-vars01-input.svelte
tests/fixtures/rules/no-immutable-reactive-statements/valid/builtin-vars02-input.svelte

fix: false positives for builtin `$$` vars in `svelte/no-immutable-reactive-statements`

---

.changeset/calm-carpets-shave.md
src/configs/all.ts
tests/src/configs/all.ts

fix: `plugin:svelte/all` config

---

.changeset/great-camels-dress.md
package.json

feat: add support for Svelte v4

---

.changeset/smart-gifts-shake.md
src/rules/no-unused-class-name.ts

fix(no-ununsed-class-name): fixed an error with @use at-rules

---

.changeset/twenty-trainers-peel.md
.eslintignore
package.json
src/rules/indent-helpers/svelte.ts
src/rules/mustache-spacing.ts
tests/fixtures/rules/indent/invalid/const-tag01-requirements.json
tests/utils/utils.ts

feat: update parser

---

.changeset/blue-plants-pump.md
src/utils/css-utils/style-attribute.ts
tests/fixtures/rules/prefer-style-directive/invalid/test04-errors.yaml
tests/fixtures/rules/prefer-style-directive/invalid/test04-input.svelte
tests/fixtures/rules/prefer-style-directive/invalid/test04-output.svelte

fix: style report location

---

README.md
docs/README.md

docs: add note for svelte v5

---

.changeset/four-yaks-protect.md
packages/eslint-plugin-svelte/package.json

fix: update svelte-eslint-parser

---

.changeset/tender-peaches-thank.md
packages/eslint-plugin-svelte/package.json

fix(deps): update dependency svelte-eslint-parser to ^0.41.0

---

.changeset/short-apricots-push.md
packages/eslint-plugin-svelte/package.json

fix: update svelte-eslint-parser to v0.42

---

packages/eslint-plugin-svelte/package.json

close: https://github.com/sveltejs/eslint-plugin-svelte/issues/952

chore: remove `lint:style`

---

README.md
docs/README.md

close https://github.com/sveltejs/eslint-plugin-svelte/issues/948

chore: update README regarding versioning policy

---

.vscode/settings.json

I need to configure this for format on save.

chore: update `vscode/settings.json`

---

packages/eslint-plugin-svelte/package.json

I need https://github.com/sveltejs/svelte-eslint-parser/pull/626

chore: update `svelte-eslint-parser` to `1.0.0-next.6`

---

.github/workflows/pkg.pr.new.yml
tools/pkg.pr.new-comment.mjs

This PR will change the job to provide a link to try it out in the playground in the PR comments.
See https://github.com/sveltejs/eslint-plugin-svelte/pull/1042#issuecomment-2614259508

chore: update pkg.pr.new job

---

docs-svelte-kit/src/lib/sidemenu/UlMenu.svelte

close #1070
I think this change will probably fix it.

chore: fix website navigation

---

.changeset/better-rice-join.md
packages/eslint-plugin-svelte/src/rules/no-useless-mustaches.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-useless-mustaches/valid/valid-test01-input.svelte

fix: account for mustache inside mustache

---

README.md
docs/user-guide.md

close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1092

chore: update README

---

packages/eslint-plugin-svelte/src/utils/svelte-context.ts

close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1120
I would like to add Windows CI but before that I've created the PR to close #1120.
https://github.com/sveltejs/eslint-plugin-svelte/pull/1122

fix: support windows path delimiter

---

.changeset/khaki-glasses-search.md

I forgot to add a changeset file in #1124, so I will add it in this PR.

chore:  add changeset for #1124

---

.changeset/wise-fireants-obey.md
packages/eslint-plugin-svelte/src/rules/no-useless-mustaches.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-useless-mustaches/invalid/quote-test02-errors.yaml
packages/eslint-plugin-svelte/tests/fixtures/rules/no-useless-mustaches/invalid/quote-test02-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-useless-mustaches/invalid/quote-test02-output.svelte

fix(no-useless-mustaches): Wrong auto-fix for quoted mustaches

---

packages/eslint-plugin-svelte/src/rules/no-unnecessary-state-wrap.ts
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unnecessary-state-wrap/valid/allow-reassign-bind1-config.json
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unnecessary-state-wrap/valid/allow-reassign-bind1-input.svelte
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unnecessary-state-wrap/valid/allow-reassign-bind2-config.json
packages/eslint-plugin-svelte/tests/fixtures/rules/no-unnecessary-state-wrap/valid/allow-reassign-bind2-input.svelte

related: https://github.com/sveltejs/eslint-plugin-svelte/issues/1180

chore: add bind tests for `no-unnecessary-state-wrap`

---

.changeset/open-ties-wash.md

https://github.com/sveltejs/eslint-plugin-svelte/pull/1187#issuecomment-2777248264

Follow-up for 1187

---

.changeset/pink-doors-rhyme.md
packages/eslint-plugin-svelte/tests/utils/utils.ts

I have already tested the changes in #1151, but decided to put them into a separate PR and they can be merged in any order :)

test: added support for .svelte.js test files

---

.github/workflows/Release.yml

Reverts sveltejs/eslint-plugin-svelte#1345

Revert "chore: try to update npm for release action"
